In [1]:
import gdown
filename = 'PtLibraryData.csv'
url = 'https://drive.google.com/uc?id=14EDAU0RhBrloiwS_ieDo7xrKb4w5wkmj'
gdown.download(url, filename, quiet=False)

ModuleNotFoundError: No module named 'gdown'

In [ ]:
# csv 파일의 인코딩을 확인할 수 있는 detect() 메서드를 가지고 있는 chardet 패키지
import chardet

# csv 파일을 읽어 변수 d에 저장하고 d의 인코딩을 확인해본다.
with open('PtLibraryData.csv', mode='rb') as f:
  d = f.readline()
print(chardet.detect(d))

# csv 파일을 읽어와 출력해보기
with open('PtLibraryData.csv') as f:
  print(f.readline())
  print(f.readline())

{'encoding': 'utf-8', 'confidence': 0.99, 'language': ''}

In [ ]:
# 데이터 프레임을 사용할 수 있는 pandas 패키지
import pandas as pd

# csv파일을 읽어 데이터프레임 객체를 생성하는 read_csv() 메서드
df = pd.read_csv('PtLibraryData.csv', encoding='utf-8', low_memory=False)

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,세이노의 가르침,세이노 지음,데이원,2023,9.79117E+12,NaN,0,NaN,199.1,1,0,2023-03-30
1,2,서울대생의 비밀과외,"소린TV,안소린 [공]지음",다산에듀,2023,9.79113E+12,NaN,1,NaN,373.7,1,0,2023-03-30
2,3,(현직 고등학교 선생님들이 직접 고른) 생기부 필독서 100,주경아 외 지음,센시오,2023,9.79117E+12,NaN,1,NaN,376.6,1,0,2023-03-30
3,4,당연하게도 나는 너를,이꽃님 지음,우리학교,2023,9.79117E+12,NaN,4,NaN,813.7,1,0,2023-03-30
4,5,고요한 우연,김수빈 지음,문학동네,2023,9.78895E+12,NaN,0,NaN,813.7,1,0,2023-03-30

In [ ]:
# to_csv()메서드를 이용해 데이터프레임 csv로 저장 
df.to_csv('ns_202303.csv')

In [ ]:
# to_csv로 저장한 데이터프레임 csv 파일 읽어오기
with open('ns_202303.csv') as f:
  for i in range(3) :
    print(f.readline(), end='')

In [ ]:
# 데이터프레임을 csv 저장한 파일 읽기
ns_df = pd.read_csv('ns_202303.csv', low_memory=False)
ns_df.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,세이노의 가르침,세이노 지음,데이원,2023,9.79117E+12,NaN,0,NaN,199.1,1,0,2023-03-30
1,2,서울대생의 비밀과외,"소린TV,안소린 [공]지음",다산에듀,2023,9.79113E+12,NaN,1,NaN,373.7,1,0,2023-03-30
2,3,(현직 고등학교 선생님들이 직접 고른) 생기부 필독서 100,주경아 외 지음,센시오,2023,9.79117E+12,NaN,1,NaN,376.6,1,0,2023-03-30
3,4,당연하게도 나는 너를,이꽃님 지음,우리학교,2023,9.79117E+12,NaN,4,NaN,813.7,1,0,2023-03-30
4,5,고요한 우연,김수빈 지음,문학동네,2023,9.78895E+12,NaN,0,NaN,813.7,1,0,2023-03-30

In [ ]:
# index_col 매개변수로 인덱스의 위치를 지정해주고 읽기
ns_df = pd.read_csv('ns_202303.csv', index_col=0, low_memory= False)
ns_df.head()

In [ ]:
# 인덱스를 빼고 저장하기
df.to_csv('ns_202303.csv', index=False)